setup:
  ansible: .prbuilds/setup.playbook.yml
teardown:
  ansible: .prbuilds/cleanup.playbook.yml
checks:
  screenshots:
    url: http://localhost:9000/books/2014/may/21/guardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism
  a11yvalidation:
    dummy: dummy
  lighthouse:
    url: http://localhost:9000/books/2014/may/21/guardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism
  loadtest:
    url: http://localhost:9000/books/2014/may/21/guardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism
  microdata:
    endpoints:
      - url: http://localhost:9000/business/live/2017/oct/09/nobel-prize-in-economics-due-to-be-unveiled-business-live
        expected:
          - WebPage
          - LiveBlogPosting
      - url: http://localhost:9000/books/2014/may/21/guardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism
        expected:
           - WebPage
           - NewsArticle 
